name: NXThemesInstaller
on:
  push:
    branches: [ master, githubCI ]
  pull_request:
    branches: [ master ]
    paths:
      - SwitchThemesNX/**
jobs:
  Build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch build script
      run: |
        sudo apt-get update
        sudo apt-get install -y p7zip-full
        cd $GITHUB_WORKSPACE/SwitchThemesNX/
        chmod +x scripts/cibuild.sh
        scripts/cibuild.sh -j4
    - uses: actions/upload-artifact@master
      with:
        name: Built
        path: ${{ github.workspace }}/SwitchThemesNX/Built.7z
